POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "public class Hello { public static void main(String[] args) { System.out.println(\"Hello World! from java\"); } }",
  "language": "java"
}

###Python###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "print('Hello World! from python')",
  "language": "python"
}

###C###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <stdio.h>\nint main() { printf(\"Hello World! from C\"); return 0; }",
  "language": "c"
}

###C++###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <iostream>\nint main() { std::cout << \"Hello World! from C++\"; return 0; }",
  "language": "cpp"
}
