POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "public class Hello { public static void main(String[] args) { System.out.println(\"Hello World! from java\"); } }",
  "language": "java"
}

###Python###
POST http://localhost:8081/api/execute
Content-Type: application/json


{
  "code": "print('Hello World! from python')",
  "language": "python"
}

###C###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <stdio.h>\nint main() { printf(\"Hello World! from C\"); return 0; }",
  "language": "c"
}

###C++###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <iostream>\nint main() { std::cout << \"Hello World! from C++\"; return 0; }",
  "language": "cpp"
}


###JavaScript###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "console.log('Hello World! from JavaScript');",
  "language": "js"
}


###Python-input###

POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "name = input()\nprint('Hello', name)",
  "language": "python",
  "stdin": "Testing input in python..."
}

###Java-input###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "import java.util.Scanner;\npublic class Hello { public static void main(String[] args) { Scanner scanner = new Scanner(System.in); String name = scanner.nextLine(); System.out.println(\"Hello \" + name); } }",
  "language": "java",
  "stdin": "Testing input in java..."
}

####C-input###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <stdio.h>\nint main() { char name[100]; scanf(\"%s\", name); printf(\"Hello %s\", name); return 0; }",
  "language": "c",
  "stdin": "TestinginputinC..."
}

###C++-input###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "#include <iostream>\n#include <string>\nint main() { std::string name; std::cin >> name; std::cout << \"Hello \" << name; return 0; }",
  "language": "cpp",
  "stdin": "TestinginputinC++..."
}


###JavaScript-input###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "process.stdin.resume();\nprocess.stdin.setEncoding('utf8');\nprocess.stdin.on('data', (name) => { console.log(`Hello ${name.trim()}`); });",
  "language": "js",
  "stdin": "TestinginputinJavaScript..."
}

###Java with error###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "public class Hello { public static void main(String[] args) { while(true){ int x = 1; } } }",
  "language": "java"
}



###job-id polling###
GET http://localhost:8081/api/result/01286d9a-efcd-4eec-9f44-1f3a57a11063
Content-Type: application/json



###Security block###
POST http://localhost:8081/api/execute
Content-Type: application/json

{
  "code": "import os\nos.system('sudo rm -rf /')",
  "language": "python"
}

###Signup###
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "testuser",
  "password": "password123"
}

###Login###
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

###Guest###
POST http://localhost:8081/api/auth/guest

###Google - open in browser###
# GET http://localhost:8081/oauth2/authorization/google


###Test protected route with Google token###
POST http://localhost:8081/api/execute
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWVzdF9kYWVlNWIwMi0zYTkwLTQzNDQtOGNmMy1kNjZhMjM1NTNkYjQiLCJpYXQiOjE3NzI5MjI2NTEsImV4cCI6MTc3MzAwOTA1MX0._UjokmXVVe2RYQ1dDsYFQUruINa7Yw-SSB6dUL3Bu-E
Content-Type: application/json

{
  "code": "print('hello world')",
  "language": "python",
  "stdin": ""
}

###Result with token###
GET http://localhost:8081/api/result/01286d9a-efcd-4eec-9f44-1f3a57a11063
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWVzdF9kYWVlNWIwMi0zYTkwLTQzNDQtOGNmMy1kNjZhMjM1NTNkYjQiLCJpYXQiOjE3NzI5MjI2NTEsImV4cCI6MTc3MzAwOTA1MX0._UjokmXVVe2RYQ1dDsYFQUruINa7Yw-SSB6dUL3Bu-E
Content-Type: application/json
