spring.application.name=backend
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/runtimedb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

redis.enabled=false

# JWT
jwt.secret=2cf187fe64326759c9c3d885ddfa2229c687a932e75e63639154ca0ba0850b3a
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
